site_name: SoftFIRE Software Documentation
pages:
        - SoftFIRE:
                - Introduction: 'index.md'
                - SoftFIRE Middleware: 'softfire-middleware.md'
                - SoftFIRE available resources: 'softfire-available-resources.md'
        - Wiki:
                - Getting Started: 'getting-started.md'
                - Experiment Manager: 'experiment-manager.md'
                - Define your experiment: 'experiment-definition.md'
                - NFV Manager: 'nfv-manager.md'
                - SDN Manager:
                  - General: 'sdn-manager.md'
                  - OpenSDNCore:
                    - Introduction: 'opensdncore.md'
                    - Controller: 'osdnc-controller.md'
                    - API Documentation: 'opensdncore-nb-api.md'
                  - OpenDaylight:
                    - Introduction: 'opendaylight.md'
                    - API Documentation: 'opendaylight-openflow-api.md'
                - Physical Device Manager: 'pd-manager.md'
                - Security Manager:
                  - General: 'security-manager.md'
                  - Firewall: 'firewall.md'
                  - Suricata NIPS: 'suricata.md'
                  - pfSense router/FW: 'pfsense.md'
                - Monitoring Manager: 'monitoring-manager.md'
        - Tutorials:
                - Nfv Tutorial:
                  -  Iperf: 'nfv-tutorial-iperf.md'
                  -  Custom: 'nfv-tutorial-custom.md'
                  -  Monitoring-VNF: 'nfv-tutorial-monitoring-vnf.md'
                - Sdn Tutorial:
                  - Sdn : 'sdn-tutorial.md'
                  - OpenSDNCore: 'osdnc-examples.md'
                  - Opendaylight : 'tutorial-iperf+odl-sdn.md'
                - Security Tutorial: 'sec-tutorial.md'
                - Monitoring Tutorial: 'mon-tutorial.md'
        - Dev:
                - Install the SoftFIRE Middleware:
                  - Code install: 'install-softfire-middleware.md'
                  - Docker install: 'install-softfire-middleware-docker.md'
                - Write a sub manager: 'sub-manager.md'
                - How to generate a certificate: 'gen-certificate.md'
                - SDN Manager developers: 'sdn-manager-dev.md'
                - SoftFIRE Integration Tests: 'integration-test.md'
        - Extras:
                - OpenVPN Manual configuration: 'openvpnconfig.md'
                - Slack User Guide: 'slack.md'

theme_dir: material
extra:
  palette:
    primary: 'deep orange'
    accent: 'orange'
  feature:
    tabs: false
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
  social:
    - type: 'github'
      link: 'https://github.com/SoftFIRE-eu'
    - type: 'slack'
      link: 'https://softfire.slack.com/'
    - type: 'docker'
      link: 'https://hub.docker.com/r/softfire/softfire-middleware/'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/company-beta/15145251/'
    - type: 'youtube'
      link: 'https://www.youtube.com/channel/UCYEe_8W-0vJ97-1OXsSjU8A'

repo_url: https://github.com/SoftFIRE-eu/experiment-manager
repo_name: SoftFIRE Experiment Manager
site_favicon: favicon.ico
markdown_extensions:
          - admonition
          - codehilite
          - footnotes
          - toc(permalink=true)
          - pymdownx.arithmatex
          - pymdownx.betterem(smart_enable=all)
          - pymdownx.caret
          - pymdownx.critic
          - pymdownx.emoji:
                    emoji_generator: !!python/name:pymdownx.emoji.to_svg
          - pymdownx.inlinehilite
          - pymdownx.magiclink
          - pymdownx.mark
          - pymdownx.smartsymbols
          - pymdownx.superfences
          - pymdownx.tasklist(custom_checkbox=true)
          - pymdownx.tilde

copyright: Copyright (c) 2016-2018 SoftFIRE (http://softfire.eu)

extra_javascript:
          - 'javascripts/extra.js'
